NASA-AMMOS/openmct-mcws

- loader.js
- src/channelTable/channelTablePlugin/ChannelTable.js
- src/channelTable/channelTablePlugin/ChannelTableRowCollection.js
- src/services/mcws/MIO.js
Overriding TableRowCollections `addRows` method to avoid sorting and to instead use the ChannelTableRowCollections `addRow` method, which handles replacing existing rows with new data, preserving the original order of the items. Also, no removing the rows directly, but emitting which rows are moved, because we handle row replacement in the `addRow` method.
Fixes issue where metadata was being `.json()`'d twice causing an error and preventing the correct version of MCWS to be set.
Sets `greedyLAD` to false, to turn off a new feature in core Open MCT that would show telemetry if it falls out of the set time bounds if no new telemetry has come in to replace it (only affects LAD requests).
Address subtask in #11
> [Channel Tables] Preserve order of channels

- package.json
- src/historical/HistoricalProvider.js
- src/persistence/MCWSPersistenceProvider.js
- src/services/mcws/DataTableMIO.js
- src/services/mcws/MIO.js
- src/services/mcws/NamespaceMIO.js
- src/services/mcws/OpaqueFileMIO.js
- src/services/mcws/mcws.js
Open MCT has the ability to cancel object requests (from the tree if a folder is closed before objects have been loaded) and telemetry requests (canceled when navigating away from a view that has requested telemetry). These changes hook that functionality up to the Historical Provider and the Persistence Provider in OMM.
> Adding abort signal for object and telemetry requests

- src/historical/HistoricalProvider.js
closes #70 
This is correctly configuration the abort signal for batch requests. This was missed in the overall abort additions.
> Fix misconfigured abort signal in batch request

- src/persistence/existingNamespaceUpdateInterceptor.js
- src/persistence/plugin.js
- src/persistence/utils.js
closes #55 
closes #59
This fix makes it so you can have an instance of OMM that doesn't have a user namespace configured. This also fixes an issue where you were unable to delete older instance objects (pre 5.0) due to mismatching composition formats.
> [Persistence] Removes required user namespace and inability to manipulate older objects

- src/persistence/MCWSPersistenceProvider.js
- src/persistence/missingUserFolderInterceptor.js
- src/persistence/plugin.js
- src/persistence/utils.js
closes #68 
Pre 5.0, OMM would create user folders without a root object inside. Once we upgraded out of legacy persistence, these objects are created when the user folder is created. In older persistence, it would not know to create the new roots in an empty folder, this fix addresses this. It will be run once per user folder and will never run again after the folder root is created, due to a flag in localStorage. Deleting this flag, will cause the checks to run again (once).
> [Persistence] Fix "missing" empty user folders from older persistence

- src/actionModifiers/plugin.js
Disabling check in import until location bug is fixed. from #81
> disable warn on multiple dataset import

- src/historical/HistoricalProvider.js
There are some endpoints that will not support all filters that are set globally. This update will allow the user to see what the error is and unset the filters if they desire.
This will only notify the user when global filters are set and the following type of response (400) is received from MCWS:
It will pull the filter that is an issue and include it in the notification.
> [Global Filters] Handle errors when endpoints don't support a filter

- package.json
- pom.xml
- src/identity/LoginService.js
- src/identity/login.html
- src/link/plugin.js
- added a url sanitizer library for links
- using it in links to sanitize user provided url
- switched to innerText for link as well
- removed an unproblematic use of innerHTML in loginService code and optimized it (loginService _may_ not be used anymore)
> Remove unnecessary `innerHTML` in code

- .github/ISSUE_TEMPLATE/commitment.md
- .github/ISSUE_TEMPLATE/defect-report.md
- .github/ISSUE_TEMPLATE/improvement.md
- .github/ISSUE_TEMPLATE/other.md
- .github/ISSUE_TEMPLATE/sustaining-activities.md
Removed some items (steps 2 - 4, seem unnecessary), criticality table (replaced with a comment of descriptions for labels), environment block (moved to "Additional Context" section). Added a reporting section in a comment, this can be scanned to pull in important information for reporting releases (note unique to each type). Added "Other" template to match reporting requirements. Pulled in additional information from reporting documents as well for more information purposes (usually in comments in the issue).
> Update issue templates for clarity and reporting purposes

- package.json
- src/services/session/SessionService.js
Closes #134 
Also bump version to 2412 build 1
> Designate time in notifications as wall clock time

- src/exportDataAction/ExportDataAction.js
- src/exportDataAction/ExportDataActionSpec.js
- src/exportDataAction/ExportDataTask.js
- src/exportDataAction/ExportDataTaskSpec.js
- src/types/TypeCompositionPolicySpec.js
closes #172 
Update unit tests for legacy angular removal.
> Update unit tests invalidated by legacy removal changes

- .webpack/webpack.prod.js
- src/persistence/BaseMCWSPersistenceProvider.js
- src/persistence/MCWSPersistenceProvider.js
- src/persistence/MCWSUserContainerProvider.js
- src/persistence/plugin.js
Closes #110 
Separated out the parent user folder into it's own provider without a `create` and `update` as it's not able to be created or updated. This will prevent the parent user folder from being available in the create menu as a location and being able to be modified with a right click.
> [Persistence] Make parent user folder unable to be modified

- src/realtime/MCWSStreamProvider.js
> Configurable "Real-time Connection Lost" Notification

- src/historical/HistoricalProvider.js
- src/historical/HistoricalProviderSpec.js
- src/multipleHistoricalSessions/indicator/historicalSessionIndicator.vue
- src/multipleHistoricalSessions/sessionSelector/historicalSessionSelector.vue
- src/services/session/SessionLocalStorageHandler.js
- src/services/session/SessionService.js
- src/services/session/SessionURLHandler.js
- src/services/session/test/service/SessionServiceSpec.js
- src/venues/VenueService.js
> Fix local storage filtering overriding historical session filtering set by url

- config.js
- src/globalFilters/FilterField.vue
- src/globalFilters/GlobalFilterSelector.vue
- src/services/filtering/FilterService.js
- src/services/filtering/FilterUrlHandler.js
Pull request adds: 
1. Documentation describing the filtering fields in config.js
2. Ability to modify the default field shown for a filtering drop down. 
3. Bugfix in filtering UI caused by trying to clone a proxy object. 
4. Change in filtering from 'small' form to 'fit' form. 
5. Changes lodash imports back so they work with the recommended 'git clone -> npm install' workflow in README.
> Fix/247 global filter UI

- config.js
Due to updates in core Open MCT in the Time Conductor, these two time systems are currently breaking. Until there is a fix we're removing them from the default config.
> Temporarily remove LMST and SCLK from default time systems in configuration

- src/persistence/MCWSPersistenceProvider.js
- src/persistence/test/MCWSNamespaceModelProviderSpec.js
- src/persistence/test/MCWSNamespaceServiceSpec.js
- src/persistence/test/MCWSPersistenceProviderSpec.js
- src/product-status/DataProductRowSpec.js
- src/services/session/test/controllers/SessionIndicatorControllerSpec.js
- src/services/session/test/controllers/SessionSelectorControllerSpec.js
- src/venues/VenueSpec.js
closes #259
Updates unit tests broken during updates/upgrades.
> [Unit Tests] Update unit tests

- src/services/session/SessionService.js
Returns two logic checks for removing sessions from current tracking and initializes and explicitly initializes an instance variable to null.
closes #244
> Fix instances of "Expression has no effect" warning in SessionService.js

- .webpack/webpack.prod.js
- package.json
- src/AMMOSPlugins.js
- src/realtime/MCWSAlarmMessageStreamProvider.js
- src/realtime/MCWSChannelStreamProvider.js
- src/realtime/MCWSCommandStreamProvider.js
- src/realtime/MCWSDataProductStreamProvider.js
- src/realtime/MCWSEVRLevelStreamProvider.js
- src/realtime/MCWSEVRStreamProvider.js
- src/realtime/MCWSFrameEventStreamProvider.js
- src/realtime/MCWSFrameSummaryStreamProvider.js
- src/realtime/MCWSMessageStreamProvider.js
- src/realtime/MCWSPacketSummaryEventProvider.js
- src/realtime/MCWSStreamProvider.js
- src/realtime/MCWSStreamWorkerScript.js
- src/realtime/plugin.js
closes #292
closes #293 
Updated Realtime code to ES6 classes/syntax.
Increase reconnect debounce time from 10ms to 100ms to add additional time for connection batching.
When closing WebSockets (due to no subscribers or because of updated filters/topics) suppress any errors. In high latency environments, these sockets can be closed before even connecting, which will throw errors. Other errors can pop up due to high latency environments that are not useful to the end user as these connections are no longer being used (either being replaced with a new connection, once that connection opens so no data is lost or because there are no subscribers). These errors just cause confusion and serve no informational purpose.
> Improved WS reconnect closures and increased connection batching interval

- config.js
- package.json
- src/time/plugin.js
This one shouldn't have any smap stuff in it.
> Fix Timesystem presets and configs

- config.js
- package.json
- src/AMMOSPlugins.js
- src/realtime/MCWSAlarmMessageStreamProvider.js
- src/realtime/MCWSChannelStreamProvider.js
- src/realtime/MCWSCommandStreamProvider.js
- src/realtime/MCWSDataProductStreamProvider.js
- src/realtime/MCWSEVRLevelStreamProvider.js
- src/realtime/MCWSEVRStreamProvider.js
- src/realtime/MCWSFrameEventStreamProvider.js
- src/realtime/MCWSFrameSummaryStreamProvider.js
- src/realtime/MCWSMessageStreamProvider.js
- src/realtime/MCWSPacketSummaryEventProvider.js
- src/realtime/MCWSStreamProvider.js
- src/realtime/MCWSStreamWorkerScript.js
- src/realtime/plugin.js
- src/services/mcws/MCWSClient.js
- src/time/plugin.js
> Backmerge `v5.3.1` into `main`

- config.js
- loader.js
- package.json
closes: #218 
This change adds new plugins to the config to be enabled from core Open MCT. They are: Time Strip, Time List, Plan, Scatter Plot.
Also, enabled the ability to add any core plugins (tested or not on our end), with a warning in the console that the plugin has not been tested.
> Enable Additional Plugins

- .webpack/webpack.prod.js
- src/persistence/BaseMCWSPersistenceProvider.js
- src/persistence/MCWSPersistenceProvider.js
- src/persistence/oldPersistenceFolderInterceptor.js
closes #240 
If there's an error getting an object that is NOT a `404`, then we return an error object, similar to how we return a missing object for missing... objects (in our case for user folders a `404` means we create the root object: https://github.com/NASA-AMMOS/openmct-mcws/blob/3f58be75b257bc6c1ce2f31d1feb06b6f735ccda/src/persistence/BaseMCWSPersistenceProvider.js#L178
This addition of returning the error object, allows us to not try to save a missing object caused from a network error (no internet for example) in the case it's from an older persistence store that had folders on the backend, but no root object : https://github.com/NASA-AMMOS/openmct-mcws/blob/3f58be75b257bc6c1ce2f31d1feb06b6f735ccda/src/persistence/oldPersistenceFolderInterceptor.js#L52
Also added a retry loop. …
> Account for network errors during user folder retrieval
