NASA-AMMOS/openmct-mcws

.gitignore
.webpack/webpack.common.js
.webpack/webpack.dev.js
.webpack/webpack.prod.js

closes #6 
Restoring our `.webpack` config and `.gitignore` file.

Restore webpack configuration files and gitignore

---

src/actionModifiers/ImportExportWithDatasets/DatasetCollection.js

Closes #9 
* retrieving dataset id
* scope recursive call
* load composition only if exists
* async fixes

fix export as json action

---

README.md
config.js

Add config file

---

src/realtime/MCWSStreamProvider.js

Partially fixes #11 
Stringify/parse was causing a circular reference issue due to changes in openmct core. This will fix that.

[Realtime] Options, shallow copy

---

package.json

change url for the repository

---

src/multipleHistoricalSessions/sessionSelector/historicalSessionSelector.vue
src/multipleHistoricalSessions/sessionTable/SessionTable.js
test_data/Session.json

Clear Historical Session table filters on close

---

src/packetQuery/components/PacketQueryView.vue

fix packet view form due to core changes

---

src/legacy/products/src/EMDViewProvider.js

fix regression in EMD viewer when switching to fetch

---

src/actionModifiers/ImportExportWithDatasets/importWithDatasetsModifier.js

fix naming conflict in import

---

src/channelTable/channelTablePlugin/ChannelTableFormatViewProvider.js
src/framesummary/FrameWatchConfigurationViewProvider.js
src/framesummary/plugin.js

View Priority fixes

---

src/persistence/existingNamespaceUpdateInterceptor.js
src/persistence/plugin.js

Add an interceptor that will update the locations of older namespaces to work with the new logic.

[MCWSPersistenceProvider] Fix issues installing over existing older namespaces

---

src/framesummary/FrameWatchRowCollection.js
src/framesummary/FrameWatchTable.js
src/framesummary/encodingwatch/EncodingWatchRow.js
src/framesummary/plugin.js

Fix frame summary view

---

src/frameaccountability/sortedEventsCollection.js

Fix sorted collection in frame accountability view

---

src/framesummary/FrameWatchTable.js
src/framesummary/encodingwatch/EncodingWatchRow.js

Fix encoding watch row reactifying datasetCache and openmct

---

src/alarmsView/AlarmsViewHistoricalContextTableRow.js

Fix Alarm row reactifying datasetCache and openmct

---

README.md

https://jira.jpl.nasa.gov/browse/OMM-152

Update verbiage for camUrl and mcwsUrl requirements

---

src/services/mcws/MCWSClient.js

Append options params to request url in case of params also defined in url

---

src/alarmsView/AlarmsTable.js
src/alarmsView/AlarmsViewHistoricalContextTableRow.js
src/alarmsView/AlarmsViewRowCollection.js
src/framesummary/FrameWatchRowCollection.js

Refactor Alarms View

---

loader.js
package.json

Add filters for recorded/realtime in evr views

---

src/historical/HistoricalProvider.js
src/realtime/MCWSStreamProvider.js
src/services/filtering/FilterService.js

disable filterService if no global filters defined

---

config.js
src/globalFilters/GlobalFilterIndicator.vue
src/globalFilters/GlobalFilterSelector.vue
src/historical/HistoricalProvider.js
src/realtime/MCWSStreamProvider.js
src/services/filtering/FilterService.js
src/services/filtering/FilterUrlHandler.js

Fixes multiple issues with global filtering

---

src/actionModifiers/MultipleDatasets/constants.js
src/actionModifiers/MultipleDatasets/warnMultipleDatasetsOnDuplicateModifier.js
src/actionModifiers/MultipleDatasets/warnMultipleDatasetsOnImportModifier.js
src/actionModifiers/plugin.js

Warn if multiple datasets

---

package.json
pom.xml

Updating rc version in package.json and pom.xml

[Version 5.1.0 Release Candidate 3] Update Versioning

---

src/customForms/UrlField/UrlField.vue

related #84 
We're targeting specific response error codes for more meaningful feedback.

[Dataset Guardrails] More targeted error handling

---

src/actionModifiers/ImportExportWithDatasets/importWithDatasetsModifier.js

closes #96 
We need to assign the changes back to the original location so they are passed through.

[Dataset] Import/Export Save Updates

---

src/channelTable/channelTablePlugin/plugin.js

add default configuration to channel table types

---

src/actionModifiers/ImportExportWithDatasets/importWithDatasetsModifier.js

replace ALL occurences of the dataset identifier

---

package.json
pom.xml
src/alarmsView/alarms-view-timeout.vue
src/alarmsView/plugin.js
src/channelTable/channelTablePlugin/ChannelTableFormatViewProvider.js
src/channelTable/channelTablePlugin/plugin.js
src/commandEventsView/plugin.js
src/evrView/EVRViewLevelsConfigurationViewProvider.js
src/evrView/plugin.js
src/messagesView/plugin.js
src/packetSummary/plugin.js
src/product-status/data-product-autoclear.vue
src/product-status/plugin.js
src/tables/VistaTableConfigurationProvider.js

Closes #37
bumps version to `5.2.0-rc1`

Various usability improvements to tabbed views

---

src/services/session/test/service/SessionServiceSpec.js

closes #116
Update older SessionService tests to work with new updated code.

[SessionService] Update tests to work with new code

---

package.json
pom.xml

This will include search performance changes from core. Updating versions as well.

2024 Dev Build 3 - Search Performance/Version Update

---

src/actionModifiers/ImportExportWithDatasets/importWithDatasetsModifier.js
src/channelTable/channelTablePlugin/ChannelTableViewProvider.js
src/services/identity/MCWSIdentityProvider.js

closes #180 
Have enabled sorting for channel tables.
Bug fixed listed in: #187 
- User provider method issue
- Inability to import a Dataset

[Channel. Tables] Enable sorting and general bug fixes

---

package.json
pom.xml

[Release] 5.3.0 RC2

---

package.json
pom.xml
src/dictionaryView/dictionaryViewProvider.js
src/dictionaryView/dictionaryViewTable.js
src/multipleHistoricalSessions/sessionTable/SessionTable.js
src/packetQuery/components/PacketQueryView.vue
src/product-status/DataProductCell.js
src/product-status/DataProductViewProvider.js
src/product-status/plugin.js

Fixes to new issues found in `r5.3.0-rc2`

---

package.json

This has been changed and tested in dev and production environments. Addresses: #245 This is also in `main`.

Update webpack to address security concern reported by dependabot

---

package.json
pom.xml

bump version of OMM for `release/5.3.1` branch to 5.3.1.
Following this PR
- when tested, tag commit for patch release 5.3.1 as `v5.3.1`
- create pr to back merge 5.3.1 into master

Bump to version 5.3.1 for patch release
